//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyWatch.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyWatch.Resources.Views.Home.Index.ru", typeof(Index_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис погоды временно недоступен..
        /// </summary>
        internal static string ApiUnavaiblable {
            get {
                return ResourceManager.GetString("ApiUnavaiblable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цельсий.
        /// </summary>
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название города..
        /// </summary>
        internal static string CityEmpty {
            get {
                return ResourceManager.GetString("CityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город не найден..
        /// </summary>
        internal static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура.
        /// </summary>
        internal static string CurrentTemperature {
            get {
                return ResourceManager.GetString("CurrentTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фаренгейт.
        /// </summary>
        internal static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура по ощущению.
        /// </summary>
        internal static string FeelsLikeTemperature {
            get {
                return ResourceManager.GetString("FeelsLikeTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влажность.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный API ключ..
        /// </summary>
        internal static string InvalidApiKey {
            get {
                return ResourceManager.GetString("InvalidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кельвин.
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мили/час.
        /// </summary>
        internal static string m_h {
            get {
                return ResourceManager.GetString("m/h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to метров/cекунду.
        /// </summary>
        internal static string m_s {
            get {
                return ResourceManager.GetString("m/s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная температура.
        /// </summary>
        internal static string MaximumTemperature {
            get {
                return ResourceManager.GetString("MaximumTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная температура.
        /// </summary>
        internal static string MinimumTemperature {
            get {
                return ResourceManager.GetString("MinimumTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погода.
        /// </summary>
        internal static string StateOfWeather {
            get {
                return ResourceManager.GetString("StateOfWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        internal static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком много запросов. Пожалуйста попробуйте позже..
        /// </summary>
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите город и выберете его из списка.
        /// </summary>
        internal static string TypeCityHint {
            get {
                return ResourceManager.GetString("TypeCityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла непредвиденная ошибка..
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восток.
        /// </summary>
        internal static string Wind_East {
            get {
                return ResourceManager.GetString("Wind_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Север.
        /// </summary>
        internal static string Wind_North {
            get {
                return ResourceManager.GetString("Wind_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Северо-восток.
        /// </summary>
        internal static string Wind_NorthEast {
            get {
                return ResourceManager.GetString("Wind_NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Северо-запад.
        /// </summary>
        internal static string Wind_NorthWest {
            get {
                return ResourceManager.GetString("Wind_NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юг.
        /// </summary>
        internal static string Wind_South {
            get {
                return ResourceManager.GetString("Wind_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юго-восток.
        /// </summary>
        internal static string Wind_SouthEast {
            get {
                return ResourceManager.GetString("Wind_SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юго-запад.
        /// </summary>
        internal static string Wind_SouthWest {
            get {
                return ResourceManager.GetString("Wind_SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запад.
        /// </summary>
        internal static string Wind_West {
            get {
                return ResourceManager.GetString("Wind_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление ветра.
        /// </summary>
        internal static string WindDirection {
            get {
                return ResourceManager.GetString("WindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость ветра.
        /// </summary>
        internal static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
    }
}
